wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.11
    code_path: code/ppo_continuous_action.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.18
    start_time: 1700640179.034552
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 16
      - 23
      - 35
      4: 3.8.18
      5: 0.13.11
      8:
      - 5
anneal_lr:
  desc: null
  value: false
batch_size:
  desc: null
  value: 10242
capture_video:
  desc: null
  value: false
checkpoint_path:
  desc: null
  value: null
clip_coef:
  desc: null
  value: 0.2
clip_vloss:
  desc: null
  value: false
cuda:
  desc: null
  value: true
ent_coef:
  desc: null
  value: 0.0
env_id:
  desc: null
  value: Wipe
exp_name:
  desc: null
  value: Joint Velocity Controller With Updated Settings
gae_lambda:
  desc: null
  value: 0.95
gamma:
  desc: null
  value: 0.99
hf_entity:
  desc: null
  value: ''
learning_rate:
  desc: null
  value: 8.0e-05
max_grad_norm:
  desc: null
  value: 0.5
minibatch_size:
  desc: null
  value: 10242
norm_adv:
  desc: null
  value: true
num_envs:
  desc: null
  value: 1
num_minibatches:
  desc: null
  value: 1
num_steps:
  desc: null
  value: 10242
save_model:
  desc: null
  value: false
seed:
  desc: null
  value: 1
target_kl:
  desc: null
  value: null
torch_deterministic:
  desc: null
  value: true
total_timesteps:
  desc: null
  value: 1000000
track:
  desc: null
  value: true
update_epochs:
  desc: null
  value: 7
upload_model:
  desc: null
  value: false
vf_coef:
  desc: null
  value: 0.5
wandb_entity:
  desc: null
  value: null
wandb_project_name:
  desc: null
  value: cleanRL
